// Province -> Kota/Kabupaten reference data for the provinces covered by
// PROVINCE_LIST in mock-data.ts. This is representative administrative data
// (not the full national dataset) used to power cascading location selects.

export const REGENCY_LIST_BY_PROVINCE: Record<string, string[]> = {
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Kepulauan Seribu",
  ],
  "Jawa Barat": [
    "Kota Bandung",
    "Kota Bekasi",
    "Kota Bogor",
    "Kota Depok",
    "Kota Cimahi",
    "Kota Sukabumi",
    "Kota Tasikmalaya",
    "Kota Cirebon",
    "Kota Banjar",
    "Kabupaten Bandung",
    "Kabupaten Bandung Barat",
    "Kabupaten Bekasi",
    "Kabupaten Bogor",
    "Kabupaten Cianjur",
    "Kabupaten Cirebon",
    "Kabupaten Garut",
    "Kabupaten Indramayu",
    "Kabupaten Karawang",
    "Kabupaten Kuningan",
    "Kabupaten Majalengka",
    "Kabupaten Purwakarta",
    "Kabupaten Subang",
    "Kabupaten Sukabumi",
    "Kabupaten Sumedang",
    "Kabupaten Tasikmalaya",
    "Kabupaten Ciamis",
    "Kabupaten Pangandaran",
  ],
  "Jawa Tengah": [
    "Kota Semarang",
    "Kota Surakarta",
    "Kota Magelang",
    "Kota Salatiga",
    "Kota Pekalongan",
    "Kota Tegal",
    "Kabupaten Banjarnegara",
    "Kabupaten Banyumas",
    "Kabupaten Batang",
    "Kabupaten Blora",
    "Kabupaten Boyolali",
    "Kabupaten Brebes",
    "Kabupaten Cilacap",
    "Kabupaten Demak",
    "Kabupaten Grobogan",
    "Kabupaten Jepara",
    "Kabupaten Karanganyar",
    "Kabupaten Kebumen",
    "Kabupaten Kendal",
    "Kabupaten Klaten",
    "Kabupaten Kudus",
    "Kabupaten Magelang",
    "Kabupaten Pati",
    "Kabupaten Pekalongan",
    "Kabupaten Pemalang",
    "Kabupaten Purbalingga",
    "Kabupaten Purworejo",
    "Kabupaten Rembang",
    "Kabupaten Semarang",
    "Kabupaten Sragen",
    "Kabupaten Sukoharjo",
    "Kabupaten Tegal",
    "Kabupaten Temanggung",
    "Kabupaten Wonogiri",
    "Kabupaten Wonosobo",
  ],
  "Jawa Timur": [
    "Kota Surabaya",
    "Kota Malang",
    "Kota Batu",
    "Kota Kediri",
    "Kota Blitar",
    "Kota Madiun",
    "Kota Mojokerto",
    "Kota Pasuruan",
    "Kota Probolinggo",
    "Kota Bekasi",
    "Kabupaten Banyuwangi",
    "Kabupaten Bangkalan",
    "Kabupaten Bojonegoro",
    "Kabupaten Bondowoso",
    "Kabupaten Gresik",
    "Kabupaten Jember",
    "Kabupaten Jombang",
    "Kabupaten Kediri",
    "Kabupaten Lamongan",
    "Kabupaten Lumajang",
    "Kabupaten Madiun",
    "Kabupaten Magetan",
    "Kabupaten Malang",
    "Kabupaten Mojokerto",
    "Kabupaten Nganjuk",
    "Kabupaten Ngawi",
    "Kabupaten Pacitan",
    "Kabupaten Pamekasan",
    "Kabupaten Pasuruan",
    "Kabupaten Ponorogo",
    "Kabupaten Probolinggo",
    "Kabupaten Sampang",
    "Kabupaten Sidoarjo",
    "Kabupaten Situbondo",
    "Kabupaten Sumenep",
    "Kabupaten Trenggalek",
    "Kabupaten Tuban",
    "Kabupaten Tulungagung",
  ],
  Banten: [
    "Kota Tangerang",
    "Kota Tangerang Selatan",
    "Kota Serang",
    "Kota Cilegon",
    "Kabupaten Tangerang",
    "Kabupaten Serang",
    "Kabupaten Lebak",
    "Kabupaten Pandeglang",
  ],
  "Sumatera Utara": [
    "Kota Medan",
    "Kota Binjai",
    "Kota Pematangsiantar",
    "Kota Sibolga",
    "Kota Tanjungbalai",
    "Kota Tebing Tinggi",
    "Kota Padang Sidempuan",
    "Kota Gunungsitoli",
    "Kabupaten Deli Serdang",
    "Kabupaten Langkat",
    "Kabupaten Karo",
    "Kabupaten Simalungun",
    "Kabupaten Asahan",
    "Kabupaten Toba",
    "Kabupaten Dairi",
    "Kabupaten Tapanuli Utara",
    "Kabupaten Tapanuli Selatan",
    "Kabupaten Tapanuli Tengah",
    "Kabupaten Labuhanbatu",
    "Kabupaten Nias",
  ],
  Bali: [
    "Kota Denpasar",
    "Kabupaten Badung",
    "Kabupaten Gianyar",
    "Kabupaten Tabanan",
    "Kabupaten Klungkung",
    "Kabupaten Bangli",
    "Kabupaten Karangasem",
    "Kabupaten Buleleng",
    "Kabupaten Jembrana",
  ],
  "Kalimantan Timur": [
    "Kota Samarinda",
    "Kota Balikpapan",
    "Kota Bontang",
    "Kabupaten Berau",
    "Kabupaten Kutai Kartanegara",
    "Kabupaten Kutai Barat",
    "Kabupaten Kutai Timur",
    "Kabupaten Paser",
    "Kabupaten Penajam Paser Utara",
    "Kabupaten Mahakam Ulu",
  ],
};

export function getRegenciesForProvince(province: string): string[] {
  return REGENCY_LIST_BY_PROVINCE[province] ?? [];
}
