import {
  AdminUser,
  AuditLogEntry,
  ComplaintCase,
  FeedbackItem,
  IncidentRecord,
  Member,
  NotificationItem,
} from "./types";

export const PLATFORM_LIST = [
  "PT Bursa Digital Nusantara",
  "PT Indodax Nasional Indonesia",
  "PT Crypto Indonesia Berkat",
  "PT Pintu Kemana Saja",
  "PT Monex Investindo Futures",
  "PT Rifan Financindo Berjangka",
  "Tidak tahu / belum terdaftar",
];

export const CATEGORY_LIST = [
  "Dana / Withdrawal",
  "Deposit",
  "Transaksi tidak dikenali",
  "Settlement / Kliring",
  "Akses akun",
  "Penutupan akun",
  "Layanan / respon platform",
  "Dugaan penipuan / fraud",
  "Dugaan pelanggaran",
  "Lainnya",
];

export const PROVINCE_LIST = [
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Banten",
  "Sumatera Utara",
  "Bali",
  "Kalimantan Timur",
];

// Platform -> Bursa / Kliring routing
export const ROUTING_MAP: Record<string, { bursa: string; kliring: string }> = {
  "PT Bursa Digital Nusantara": { bursa: "Bursa Komoditi Nusantara", kliring: "Kliring Berjangka Indonesia" },
  "PT Indodax Nasional Indonesia": { bursa: "Bursa Aset Kripto Indonesia", kliring: "Kliring Aset Digital Nusantara" },
  "PT Crypto Indonesia Berkat": { bursa: "Bursa Aset Kripto Indonesia", kliring: "Kliring Aset Digital Nusantara" },
  "PT Pintu Kemana Saja": { bursa: "Bursa Aset Kripto Indonesia", kliring: "Kliring Aset Digital Nusantara" },
  "PT Monex Investindo Futures": { bursa: "Bursa Berjangka Jakarta", kliring: "Kliring Berjangka Indonesia" },
  "PT Rifan Financindo Berjangka": { bursa: "Bursa Berjangka Jakarta", kliring: "Kliring Berjangka Indonesia" },
};

// Context entities used by the member portals in this demo
export const ACTIVE_PLATFORM = "PT Bursa Digital Nusantara";
export const ACTIVE_BURSA = "Bursa Berjangka Jakarta"; // oversees Monex & Rifan
export const ACTIVE_KLIRING = "Kliring Berjangka Indonesia"; // serves Bursa Digital Nusantara, Monex, Rifan

export const CASES: ComplaintCase[] = [
  {
    ticket: "BPP-2026-000184",
    title: "Penarikan dana belum diterima",
    platform: "PT Bursa Digital Nusantara",
    bursaEntity: "Bursa Komoditi Nusantara",
    kliringEntity: "Kliring Berjangka Indonesia",
    category: "Dana / Withdrawal",
    subcategory: "Penarikan dana tertunda",
    severity: "Tinggi",
    status: "Diproses",
    currentOwner: "Platform",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Mendekati SLA",
    slaDeadline: "16 Jun 2026, 10:00",
    createdAt: "12 Jun 2026, 09:14",
    updatedAt: "14 Jun 2026, 15:40",
    amount: 25000000,
    transactionRef: "WD-88213471",
    platformUserId: "USR-1029384",
    chronology:
      "Pelapor mengajukan penarikan dana sebesar Rp25.000.000 pada 11 Juni 2026. Status pada aplikasi menunjukkan 'diproses' selama lebih dari 48 jam tanpa pembaruan, dan dana belum masuk ke rekening tujuan.",
    expectedResolution: "Dana penarikan segera diteruskan ke rekening tujuan dan diberikan konfirmasi tertulis.",
    evidences: ["Bukti transfer.pdf", "Screenshot status withdrawal.png", "Riwayat percakapan CS.png"],
    reporterName: "Andra Wicaksono",
    reporterCity: "Jakarta Selatan, DKI Jakarta",
    timeline: [
      { datetime: "12 Jun 2026, 09:14", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000184 dibuat otomatis.", status: "info" },
      { datetime: "12 Jun 2026, 11:02", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Pengaduan memenuhi kelengkapan dokumen minimum.", status: "success" },
      { datetime: "12 Jun 2026, 11:05", actor: "Sistem", role: "Bappebti", action: "Kasus diteruskan ke platform", note: "Current owner dipindahkan ke PT Bursa Digital Nusantara.", status: "info" },
      { datetime: "13 Jun 2026, 08:30", actor: "Tim Operasional Platform", role: "Platform", action: "Investigasi dimulai", note: "Tim sedang memeriksa status transaksi penarikan pada sistem internal.", status: "info" },
      { datetime: "14 Jun 2026, 15:40", actor: "Tim Operasional Platform", role: "Platform", action: "Menunggu konfirmasi bank", note: "Permintaan konfirmasi dikirim ke bank kustodian, menunggu balasan.", status: "warning" },
    ],
    clarifications: [
      { from: "Tim Operasional Platform", role: "Platform", datetime: "13 Jun 2026, 08:35", message: "Mohon konfirmasi nomor rekening tujuan penarikan untuk pengecekan lebih lanjut." },
      { from: "Andra Wicaksono", role: "Pelapor", datetime: "13 Jun 2026, 10:12", message: "Nomor rekening tujuan adalah BCA 1234567890 a.n. Andra Wicaksono, sesuai data terdaftar.", kind: "reply" },
    ],
    workflowState: "MEMBER_INVESTIGATION",
    publicStatus: "Sedang Diinvestigasi",
    reporter: {
      reporterType: "Perorangan",
      verifiedEmail: "andra.wicaksono@email.com",
      verifiedPhone: "+62 812-3456-7890",
      province: "DKI Jakarta",
      city: "Jakarta Selatan",
      vulnerableConsumer: false,
      preferredChannel: "Email",
      consentStatus: "Diberikan",
    },
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Bursa Digital Nusantara",
      currentActionOwner: "Platform",
      caseOfficer: "Rina Kusuma",
      supportingInstitutions: [],
      bursa: "Bursa Komoditi Nusantara",
      clearing: "Kliring Berjangka Indonesia",
      decisionAuthority: "Bappebti Case Officer",
      escalationLevel: 0,
    },
    financialExposure: 25000000,
    massIncident: true,
    parentIncidentId: "INC-2026-004",
  },
  {
    ticket: "BPP-2026-000185",
    title: "Transaksi tidak dikenali pada akun",
    platform: "PT Crypto Indonesia Berkat",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Transaksi tidak dikenali",
    subcategory: "Transaksi tanpa otorisasi",
    severity: "Kritis",
    status: "Diproses",
    currentOwner: "Bappebti",
    responsibility: "BAPPEBTI OWNED",
    slaStatus: "Lewat SLA",
    slaDeadline: "13 Jun 2026, 17:00",
    createdAt: "10 Jun 2026, 13:21",
    updatedAt: "15 Jun 2026, 09:10",
    amount: 158000000,
    transactionRef: "TX-77451209",
    platformUserId: "USR-5512098",
    chronology:
      "Pelapor menemukan tiga transaksi penjualan aset senilai total Rp158.000.000 yang tidak pernah dilakukan olehnya. Pelapor menduga adanya akses tidak sah ke akun. Platform belum memberikan tanggapan memadai setelah lebih dari 72 jam.",
    expectedResolution: "Investigasi menyeluruh atas akses akun dan pengembalian dana/aset bila terbukti transaksi tidak sah.",
    evidences: ["Bukti transfer.pdf", "Screenshot status withdrawal.png", "Riwayat percakapan CS.png"],
    reporterName: "Melisa Hartono",
    reporterCity: "Surabaya, Jawa Timur",
    escalationReason: "Platform tidak memberikan tanggapan substantif dalam batas waktu SLA dan indikasi fraud bernilai tinggi.",
    timeline: [
      { datetime: "10 Jun 2026, 13:21", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000185 dibuat otomatis.", status: "info" },
      { datetime: "10 Jun 2026, 14:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Kategori dugaan fraud, diteruskan ke platform dengan prioritas tinggi.", status: "success" },
      { datetime: "11 Jun 2026, 09:00", actor: "Tim CS Platform", role: "Platform", action: "Permintaan data tambahan", note: "Platform meminta salinan identitas tambahan untuk verifikasi.", status: "info" },
      { datetime: "13 Jun 2026, 17:00", actor: "Sistem", role: "Sistem", action: "SLA terlampaui", note: "Tidak ada tindak lanjut substantif dari platform dalam batas waktu.", status: "danger" },
      { datetime: "14 Jun 2026, 10:15", actor: "Dewi Anjani", role: "Bappebti", action: "Kasus diambil alih", note: "Bappebti mengambil alih kasus sebagai BAPPEBTI OWNED karena indikasi fraud bernilai tinggi.", status: "danger" },
      { datetime: "15 Jun 2026, 09:10", actor: "Dewi Anjani", role: "Bappebti", action: "Permintaan penjelasan resmi", note: "Surat permintaan penjelasan resmi dikirim ke manajemen platform.", status: "warning" },
    ],
    clarifications: [
      { from: "Tim CS Platform", role: "Platform", datetime: "11 Jun 2026, 09:02", message: "Mohon kirimkan ulang foto KTP dan selfie untuk proses verifikasi keamanan akun." },
      { from: "Melisa Hartono", role: "Pelapor", datetime: "11 Jun 2026, 12:40", message: "Dokumen sudah dikirimkan melalui email dukungan sejak tanggal pendaftaran, mohon segera ditindaklanjuti." },
    ],
    relatedCases: ["BPP-2026-000192"],
    workflowState: "BAPPEBTI_SUPERVISOR_REVIEW",
    publicStatus: "Dalam Review Bappebti",
    suspectedFraud: true,
    activeSecurityRisk: true,
    financialExposure: 158000000,
    reporter: {
      reporterType: "Perorangan",
      verifiedEmail: "melisa.hartono@email.com",
      verifiedPhone: "+62 813-9988-2211",
      province: "Jawa Timur",
      city: "Surabaya",
      vulnerableConsumer: false,
      preferredChannel: "WhatsApp",
      consentStatus: "Diberikan",
    },
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Crypto Indonesia Berkat",
      currentActionOwner: "Bappebti",
      caseOfficer: "Dewi Anjani",
      supportingInstitutions: [],
      bursa: "Bursa Aset Kripto Indonesia",
      clearing: "Kliring Aset Digital Nusantara",
      decisionAuthority: "Bappebti Supervisor",
      escalationLevel: 3,
      escalationReason: "Platform tidak memberikan tanggapan substantif dalam batas waktu SLA dan indikasi fraud bernilai tinggi.",
    },
    internalNotes: [
      {
        author: "Dewi Anjani",
        role: "Bappebti Case Officer",
        institution: "Bappebti",
        timestamp: "14 Jun 2026, 10:20",
        classification: "Operasional",
        text: "Riwayat login akun menunjukkan akses dari perangkat dan lokasi yang tidak dikenali pelapor pada rentang waktu transaksi tidak sah terjadi.",
        visibility: "internal",
      },
      {
        author: "Bambang Setiawan",
        role: "Bappebti Supervisor",
        institution: "Bappebti",
        timestamp: "15 Jun 2026, 09:00",
        classification: "Supervisi",
        text: "Perlu ditentukan apakah kasus ini dieskalasi ke unit Penegakan mengingat nilai kerugian tinggi dan indikasi keterlambatan respons platform yang berulang.",
        visibility: "internal",
      },
    ],
  },
  {
    ticket: "BPP-2026-000186",
    title: "Saldo aset tidak sesuai setelah settlement",
    platform: "PT Pintu Kemana Saja",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Settlement / Kliring",
    subcategory: "Selisih saldo pasca settlement",
    severity: "Sedang",
    status: "Diproses",
    currentOwner: "Kliring",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Aman",
    slaDeadline: "17 Jun 2026, 12:00",
    createdAt: "13 Jun 2026, 10:05",
    updatedAt: "15 Jun 2026, 08:20",
    amount: 4200000,
    transactionRef: "STL-2026-06-330217",
    platformUserId: "USR-3098221",
    chronology:
      "Setelah proses settlement harian, saldo aset pelapor berkurang Rp4.200.000 dari nilai yang seharusnya. Platform menyatakan selisih terjadi pada proses rekonsiliasi kliring dan meneruskan kasus untuk pengecekan referensi settlement.",
    expectedResolution: "Rekonsiliasi ulang batch settlement dan penyesuaian saldo sesuai data transaksi yang valid.",
    evidences: ["Bukti transfer.pdf", "Screenshot status withdrawal.png"],
    reporterName: "Fajar Nugroho",
    reporterCity: "Bandung, Jawa Barat",
    reconciliationIssue: "Mismatch nilai settlement pada batch STL-2026-06-330217",
    timeline: [
      { datetime: "13 Jun 2026, 10:05", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000186 dibuat otomatis.", status: "info" },
      { datetime: "13 Jun 2026, 11:30", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Kategori settlement, diteruskan ke platform.", status: "success" },
      { datetime: "13 Jun 2026, 14:00", actor: "Tim Operasional Platform", role: "Platform", action: "Diteruskan ke kliring", note: "Platform meneruskan kasus ke Kliring Aset Digital Nusantara untuk pengecekan batch settlement.", status: "info" },
      { datetime: "14 Jun 2026, 09:00", actor: "Tim Rekonsiliasi Kliring", role: "Kliring", action: "Pengecekan batch settlement", note: "Ditemukan indikasi mismatch pada batch STL-2026-06-330217, menunggu data tambahan dari platform.", status: "warning" },
      { datetime: "15 Jun 2026, 08:20", actor: "Tim Rekonsiliasi Kliring", role: "Kliring", action: "Permintaan data platform", note: "Meminta data transaksi rinci dari platform untuk proses rekonsiliasi.", status: "info" },
    ],
    clarifications: [
      { from: "Tim Rekonsiliasi Kliring", role: "Kliring", datetime: "14 Jun 2026, 09:05", message: "Mohon platform mengirimkan rincian transaksi batch STL-2026-06-330217 untuk akun terkait.", kind: "formal-request" },
    ],
    workflowState: "WAITING_SUPPORTING_INSTITUTION",
    publicStatus: "Sedang Diinvestigasi",
    financialExposure: 4200000,
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Pintu Kemana Saja",
      currentActionOwner: "Kliring",
      caseOfficer: "Sari Wulandari",
      supportingInstitutions: ["PT Pintu Kemana Saja"],
      bursa: "Bursa Aset Kripto Indonesia",
      clearing: "Kliring Aset Digital Nusantara",
      decisionAuthority: "Bappebti Case Officer",
      escalationLevel: 0,
    },
  },
  {
    ticket: "BPP-2026-000187",
    title: "Platform tidak merespons selama 3 hari",
    platform: "PT Monex Investindo Futures",
    bursaEntity: "Bursa Berjangka Jakarta",
    kliringEntity: "Kliring Berjangka Indonesia",
    category: "Layanan / respon platform",
    subcategory: "Tidak ada respon dari platform",
    severity: "Tinggi",
    status: "Menunggu Klarifikasi",
    currentOwner: "Bursa",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Lewat SLA",
    slaDeadline: "13 Jun 2026, 09:00",
    createdAt: "09 Jun 2026, 09:00",
    updatedAt: "15 Jun 2026, 10:00",
    transactionRef: "CS-2026-44210",
    platformUserId: "USR-8821093",
    chronology:
      "Pelapor mengajukan pertanyaan terkait status akun melalui layanan pelanggan platform sejak 8 Juni 2026 namun tidak mendapatkan tanggapan apapun selama lebih dari 3 hari kerja.",
    expectedResolution: "Platform memberikan tanggapan resmi atas pertanyaan pelapor dan menjelaskan status akun.",
    evidences: ["Riwayat percakapan CS.png"],
    reporterName: "Sutejo Wahid",
    reporterCity: "Semarang, Jawa Tengah",
    escalationReason: "Tidak ada respon dari platform melebihi 3 hari kerja sehingga dieskalasikan ke Bursa untuk supervisi.",
    timeline: [
      { datetime: "09 Jun 2026, 09:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000187 dibuat otomatis.", status: "info" },
      { datetime: "09 Jun 2026, 10:30", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Monex Investindo Futures.", status: "success" },
      { datetime: "13 Jun 2026, 09:00", actor: "Sistem", role: "Sistem", action: "SLA terlampaui", note: "Platform belum memberikan respon dalam batas waktu SLA.", status: "danger" },
      { datetime: "14 Jun 2026, 13:20", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Kasus dieskalasi ke Bursa", note: "Bursa Berjangka Jakarta mengambil kasus untuk supervisi langsung terhadap platform.", status: "warning" },
      { datetime: "15 Jun 2026, 10:00", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Pengingat dikirim ke platform", note: "Surat pengingat resmi dikirimkan kepada manajemen PT Monex Investindo Futures.", status: "info" },
    ],
    clarifications: [
      { from: "Tim Supervisi Bursa", role: "Bursa", datetime: "15 Jun 2026, 10:05", message: "Diminta penjelasan resmi atas keterlambatan respon kepada pelapor dalam waktu 2 hari kerja." },
    ],
  },
  {
    ticket: "BPP-2026-000188",
    title: "Penutupan akun belum diproses",
    platform: "PT Indodax Nasional Indonesia",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Penutupan akun",
    subcategory: "Permintaan penutupan akun",
    severity: "Rendah",
    status: "Resolusi Diajukan",
    currentOwner: "Pelapor",
    responsibility: "WAITING PUBLIC",
    slaStatus: "Aman",
    slaDeadline: "18 Jun 2026, 17:00",
    createdAt: "08 Jun 2026, 14:00",
    updatedAt: "14 Jun 2026, 16:45",
    platformUserId: "USR-2209817",
    chronology:
      "Pelapor mengajukan permintaan penutupan akun sejak 5 Juni 2026 namun status akun masih aktif. Platform telah memproses penutupan dan mengajukan resolusi kepada pelapor untuk konfirmasi.",
    expectedResolution: "Akun dinyatakan ditutup secara resmi dan dikonfirmasi melalui email.",
    evidences: ["Screenshot status withdrawal.png"],
    reporterName: "Yuni Astuti",
    reporterCity: "Denpasar, Bali",
    resolutionProposal: "Akun telah dinonaktifkan secara permanen pada 14 Juni 2026. Mohon konfirmasi penerimaan resolusi.",
    timeline: [
      { datetime: "08 Jun 2026, 14:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000188 dibuat otomatis.", status: "info" },
      { datetime: "08 Jun 2026, 15:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Indodax Nasional Indonesia.", status: "success" },
      { datetime: "10 Jun 2026, 11:00", actor: "Tim Operasional Platform", role: "Platform", action: "Proses penutupan akun", note: "Permintaan penutupan akun diproses pada sistem internal.", status: "info" },
      { datetime: "14 Jun 2026, 16:45", actor: "Tim Operasional Platform", role: "Platform", action: "Resolusi diajukan", note: "Akun telah dinonaktifkan, menunggu konfirmasi penerimaan dari pelapor.", status: "success" },
    ],
    clarifications: [],
    workflowState: "WAITING_REPORTER_DECISION",
    publicStatus: "Solusi Diajukan",
    reporter: {
      reporterType: "Perorangan",
      verifiedEmail: "yuni.astuti@email.com",
      verifiedPhone: "+62 851-2233-4455",
      province: "Bali",
      city: "Denpasar",
      vulnerableConsumer: false,
      preferredChannel: "Email",
      consentStatus: "Diberikan",
    },
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Indodax Nasional Indonesia",
      currentActionOwner: "Pelapor",
      caseOfficer: "Dewi Anjani",
      supportingInstitutions: [],
      bursa: "Bursa Aset Kripto Indonesia",
      clearing: "Kliring Aset Digital Nusantara",
      decisionAuthority: "Bappebti Case Officer",
      escalationLevel: 0,
    },
    resolution: {
      proposal: "Akun telah dinonaktifkan secara permanen pada 14 Juni 2026. Mohon konfirmasi penerimaan resolusi.",
      resolutionType: "Penutupan Akun",
      proposedBy: "PT Indodax Nasional Indonesia",
      proposedDate: "14 Jun 2026",
      nonMonetaryAction: "Penutupan permanen akun pengguna dan penghapusan akses aplikasi.",
      implementationDeadline: "16 Jun 2026",
      implementationEvidence: ["Konfirmasi penutupan akun.pdf"],
      bappebtiDecision: "Menunggu Review",
    },
  },
  {
    ticket: "BPP-2026-000189",
    title: "Dugaan penipuan investasi berkedok robot trading",
    platform: "PT Rifan Financindo Berjangka",
    bursaEntity: "Bursa Berjangka Jakarta",
    kliringEntity: "Kliring Berjangka Indonesia",
    category: "Dugaan penipuan / fraud",
    subcategory: "Robot trading tanpa izin",
    severity: "Kritis",
    status: "Diproses",
    currentOwner: "Bappebti",
    responsibility: "BAPPEBTI OWNED",
    slaStatus: "Mendekati SLA",
    slaDeadline: "16 Jun 2026, 17:00",
    createdAt: "11 Jun 2026, 08:40",
    updatedAt: "15 Jun 2026, 11:00",
    amount: 320000000,
    transactionRef: "INV-2026-90011",
    platformUserId: "USR-7765432",
    chronology:
      "Pelapor menginvestasikan dana melalui mitra pemasaran yang mengklaim bekerja sama dengan platform untuk layanan robot trading otomatis. Dana sebesar Rp320.000.000 tidak dapat ditarik dan mitra tidak dapat dihubungi kembali.",
    expectedResolution: "Investigasi keterkaitan platform dengan mitra pemasaran serta upaya pengembalian dana pelapor.",
    evidences: ["Bukti transfer.pdf", "Riwayat percakapan CS.png"],
    reporterName: "Ahmad Sutrisno",
    reporterCity: "Medan, Sumatera Utara",
    escalationReason: "Indikasi penipuan berskala besar dengan dugaan keterlibatan pihak ketiga yang mengatasnamakan platform berizin.",
    timeline: [
      { datetime: "11 Jun 2026, 08:40", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000189 dibuat otomatis.", status: "info" },
      { datetime: "11 Jun 2026, 09:30", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Kategori dugaan fraud nilai tinggi, langsung diklasifikasikan sebagai BAPPEBTI OWNED.", status: "success" },
      { datetime: "12 Jun 2026, 10:00", actor: "Rangga Saputra", role: "Bappebti", action: "Permintaan penjelasan anggota", note: "Diminta penjelasan resmi dari PT Rifan Financindo Berjangka terkait hubungan dengan mitra pemasaran dimaksud.", status: "warning" },
      { datetime: "15 Jun 2026, 11:00", actor: "Rangga Saputra", role: "Bappebti", action: "Eskalasi ke Penegakan", note: "Kasus dieskalasi ke unit Penegakan untuk investigasi lebih lanjut atas dugaan pelanggaran.", status: "danger" },
    ],
    clarifications: [
      { from: "Rangga Saputra", role: "Bappebti", datetime: "12 Jun 2026, 10:05", message: "Mohon konfirmasi apakah pihak yang disebutkan pelapor merupakan mitra resmi atau agen terdaftar dari platform.", kind: "formal-request" },
    ],
    workflowState: "ENFORCEMENT_REVIEW",
    publicStatus: "Dalam Review Bappebti",
    suspectedFraud: true,
    illegalEntitySuspected: true,
    financialExposure: 320000000,
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Rifan Financindo Berjangka",
      currentActionOwner: "Bappebti",
      caseOfficer: "Rangga Saputra",
      supportingInstitutions: [],
      bursa: "Bursa Berjangka Jakarta",
      clearing: "Kliring Berjangka Indonesia",
      decisionAuthority: "Bappebti Enforcement",
      escalationLevel: 4,
      escalationReason: "Indikasi penipuan berskala besar dengan dugaan keterlibatan pihak ketiga yang mengatasnamakan platform berizin.",
    },
    internalNotes: [
      {
        author: "Rangga Saputra",
        role: "Bappebti Case Officer",
        institution: "Bappebti",
        timestamp: "15 Jun 2026, 11:10",
        classification: "Penegakan",
        text: "Mitra pemasaran yang disebutkan pelapor tidak terdaftar dalam basis data agen resmi platform. Direkomendasikan investigasi lanjutan oleh unit Penegakan dan koordinasi dengan pihak kepolisian bila ditemukan indikasi pidana.",
        visibility: "internal",
      },
    ],
  },
  {
    ticket: "BPP-2026-000190",
    title: "Deposit tidak masuk ke saldo akun",
    platform: "PT Indodax Nasional Indonesia",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Deposit",
    subcategory: "Deposit tidak terverifikasi",
    severity: "Tinggi",
    status: "Diproses",
    currentOwner: "Platform",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Mendekati SLA",
    slaDeadline: "16 Jun 2026, 09:00",
    createdAt: "13 Jun 2026, 16:00",
    updatedAt: "15 Jun 2026, 09:45",
    amount: 12500000,
    transactionRef: "DP-2026-119283",
    platformUserId: "USR-4456721",
    chronology:
      "Pelapor melakukan deposit sebesar Rp12.500.000 melalui transfer bank pada 13 Juni 2026, namun saldo pada akun platform belum bertambah hingga saat ini.",
    expectedResolution: "Saldo deposit segera dikreditkan ke akun pelapor sesuai bukti transfer yang dilampirkan.",
    evidences: ["Bukti transfer.pdf"],
    reporterName: "Citra Lestari",
    reporterCity: "Jakarta Timur, DKI Jakarta",
    timeline: [
      { datetime: "13 Jun 2026, 16:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000190 dibuat otomatis.", status: "info" },
      { datetime: "13 Jun 2026, 17:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Indodax Nasional Indonesia.", status: "success" },
      { datetime: "14 Jun 2026, 09:00", actor: "Tim Operasional Platform", role: "Platform", action: "Investigasi dimulai", note: "Tim sedang melakukan pengecekan terhadap mutasi rekening penampungan deposit.", status: "info" },
      { datetime: "15 Jun 2026, 09:45", actor: "Tim Operasional Platform", role: "Platform", action: "Menunggu bukti tambahan", note: "Meminta bukti transfer dengan resolusi lebih tinggi dari pelapor.", status: "warning" },
    ],
    clarifications: [
      { from: "Tim Operasional Platform", role: "Platform", datetime: "15 Jun 2026, 09:46", message: "Mohon unggah ulang bukti transfer dengan kualitas gambar yang lebih jelas, termasuk nomor referensi bank.", kind: "formal-request" },
    ],
    massIncident: true,
    parentIncidentId: "INC-2026-004",
    financialExposure: 12500000,
  },
  {
    ticket: "BPP-2026-000191",
    title: "Permintaan klarifikasi data referensi settlement",
    platform: "PT Bursa Digital Nusantara",
    bursaEntity: "Bursa Komoditi Nusantara",
    kliringEntity: "Kliring Berjangka Indonesia",
    category: "Settlement / Kliring",
    subcategory: "Referensi settlement tidak ditemukan",
    severity: "Sedang",
    status: "Menunggu Klarifikasi",
    currentOwner: "Kliring",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Aman",
    slaDeadline: "18 Jun 2026, 12:00",
    createdAt: "14 Jun 2026, 09:30",
    updatedAt: "15 Jun 2026, 13:00",
    amount: 7800000,
    transactionRef: "STL-2026-06-330452",
    platformUserId: "USR-6612345",
    chronology:
      "Pelapor melaporkan bahwa hasil settlement transaksi tanggal 12 Juni 2026 tidak tercatat pada riwayat akun meski saldo telah terpotong sesuai posisi transaksi.",
    expectedResolution: "Penyesuaian saldo akun sesuai hasil rekonsiliasi referensi settlement.",
    evidences: ["Screenshot status withdrawal.png"],
    reporterName: "Bagas Pratama",
    reporterCity: "Yogyakarta",
    reconciliationIssue: "Referensi settlement STL-2026-06-330452 belum dikonfirmasi bank",
    timeline: [
      { datetime: "14 Jun 2026, 09:30", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000191 dibuat otomatis.", status: "info" },
      { datetime: "14 Jun 2026, 10:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Bursa Digital Nusantara.", status: "success" },
      { datetime: "14 Jun 2026, 14:00", actor: "Tim Operasional Platform", role: "Platform", action: "Diteruskan ke kliring", note: "Diteruskan ke Kliring Berjangka Indonesia untuk verifikasi referensi settlement.", status: "info" },
      { datetime: "15 Jun 2026, 13:00", actor: "Tim Rekonsiliasi Kliring", role: "Kliring", action: "Menunggu konfirmasi bank", note: "Referensi settlement masih dalam proses konfirmasi pihak bank.", status: "warning" },
    ],
    clarifications: [],
  },
  {
    ticket: "BPP-2026-000192",
    title: "Akses akun diblokir tanpa pemberitahuan",
    platform: "PT Crypto Indonesia Berkat",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Akses akun",
    subcategory: "Akun terkunci / diblokir",
    severity: "Sedang",
    status: "Diproses",
    currentOwner: "Platform",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Aman",
    slaDeadline: "17 Jun 2026, 17:00",
    createdAt: "14 Jun 2026, 12:00",
    updatedAt: "15 Jun 2026, 08:00",
    platformUserId: "USR-5512098",
    chronology:
      "Akun pelapor tiba-tiba tidak dapat diakses sejak 13 Juni 2026 tanpa pemberitahuan apapun dari platform. Pelapor menduga hal ini terkait dengan kasus transaksi tidak dikenali yang sebelumnya dilaporkan.",
    expectedResolution: "Penjelasan alasan pemblokiran akun dan pemulihan akses bila tidak terkait pelanggaran oleh pelapor.",
    evidences: ["Screenshot status withdrawal.png"],
    reporterName: "Melisa Hartono",
    reporterCity: "Surabaya, Jawa Timur",
    relatedCases: ["BPP-2026-000185"],
    timeline: [
      { datetime: "14 Jun 2026, 12:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000192 dibuat otomatis, terindikasi terkait dengan tiket BPP-2026-000185.", status: "info" },
      { datetime: "14 Jun 2026, 13:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Crypto Indonesia Berkat dengan catatan kasus terkait.", status: "success" },
      { datetime: "15 Jun 2026, 08:00", actor: "Tim Keamanan Platform", role: "Platform", action: "Investigasi keamanan", note: "Pemblokiran terkait proses investigasi keamanan akun yang sedang berjalan.", status: "info" },
    ],
    clarifications: [],
  },
  {
    ticket: "BPP-2026-000193",
    title: "Eskalasi keterlambatan penyelesaian kasus platform",
    platform: "PT Monex Investindo Futures",
    bursaEntity: "Bursa Berjangka Jakarta",
    kliringEntity: "Kliring Berjangka Indonesia",
    category: "Layanan / respon platform",
    subcategory: "Keterlambatan penyelesaian",
    severity: "Tinggi",
    status: "Diproses",
    currentOwner: "Bursa",
    responsibility: "MEMBER ASSIGNED",
    slaStatus: "Lewat SLA",
    slaDeadline: "14 Jun 2026, 17:00",
    createdAt: "07 Jun 2026, 10:00",
    updatedAt: "15 Jun 2026, 09:30",
    transactionRef: "CS-2026-44087",
    platformUserId: "USR-9981023",
    chronology:
      "Kasus terkait keluhan respon transaksi yang telah melewati dua kali perpanjangan SLA tanpa penyelesaian dari platform, sehingga diteruskan kepada Bursa untuk supervisi lanjutan.",
    expectedResolution: "Bursa memberikan arahan supervisi dan memastikan platform menuntaskan kasus dalam batas waktu baru.",
    evidences: ["Riwayat percakapan CS.png"],
    reporterName: "Galih Saputro",
    reporterCity: "Surakarta, Jawa Tengah",
    escalationReason: "Dua kali perpanjangan SLA tanpa progres signifikan dari platform.",
    timeline: [
      { datetime: "07 Jun 2026, 10:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000193 dibuat otomatis.", status: "info" },
      { datetime: "09 Jun 2026, 10:00", actor: "Sistem", role: "Sistem", action: "Perpanjangan SLA pertama", note: "SLA diperpanjang 48 jam atas permintaan platform.", status: "warning" },
      { datetime: "12 Jun 2026, 10:00", actor: "Sistem", role: "Sistem", action: "Perpanjangan SLA kedua", note: "SLA diperpanjang kembali 48 jam.", status: "warning" },
      { datetime: "14 Jun 2026, 17:00", actor: "Sistem", role: "Sistem", action: "SLA terlampaui", note: "Tidak ada penyelesaian setelah dua kali perpanjangan.", status: "danger" },
      { datetime: "15 Jun 2026, 09:30", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Kasus diambil alih Bursa", note: "Bursa Berjangka Jakarta mengambil alih supervisi penyelesaian kasus.", status: "warning" },
    ],
    clarifications: [],
  },
  {
    ticket: "BPP-2026-000194",
    title: "Pengaduan baru menunggu verifikasi sistem",
    platform: "PT Pintu Kemana Saja",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Layanan / respon platform",
    subcategory: "Permintaan informasi",
    severity: "Rendah",
    status: "Baru",
    currentOwner: "Pelapor",
    responsibility: "WAITING PUBLIC",
    slaStatus: "Aman",
    slaDeadline: "16 Jun 2026, 14:30",
    createdAt: "15 Jun 2026, 14:30",
    updatedAt: "15 Jun 2026, 14:30",
    platformUserId: "USR-3320981",
    chronology:
      "Pelapor menanyakan kejelasan biaya layanan yang dikenakan pada transaksi terakhir dan meminta rincian komponen biaya.",
    expectedResolution: "Penjelasan rinci komponen biaya transaksi yang dikenakan.",
    evidences: [],
    reporterName: "Putri Ramadhani",
    reporterCity: "Balikpapan, Kalimantan Timur",
    timeline: [
      { datetime: "15 Jun 2026, 14:30", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000194 dibuat otomatis, menunggu verifikasi sistem.", status: "info" },
    ],
    clarifications: [],
  },
  {
    ticket: "BPP-2026-000195",
    title: "Sengketa kepemilikan dana setelah penutupan akun",
    platform: "PT Indodax Nasional Indonesia",
    bursaEntity: "Bursa Aset Kripto Indonesia",
    kliringEntity: "Kliring Aset Digital Nusantara",
    category: "Penutupan akun",
    subcategory: "Sengketa dana pasca penutupan",
    severity: "Kritis",
    status: "Diproses",
    currentOwner: "Bappebti",
    responsibility: "BAPPEBTI OWNED",
    slaStatus: "Mendekati SLA",
    slaDeadline: "16 Jun 2026, 12:00",
    createdAt: "12 Jun 2026, 11:00",
    updatedAt: "15 Jun 2026, 14:00",
    amount: 89000000,
    transactionRef: "CLS-2026-22310",
    platformUserId: "USR-1102938",
    chronology:
      "Setelah proses penutupan akun, saldo dana sebesar Rp89.000.000 milik pelapor tidak dikembalikan dan platform menyatakan dana telah ditransfer ke rekening yang tidak dikenali pelapor. Terdapat dugaan sengketa kepemilikan rekening tujuan.",
    expectedResolution: "Pelacakan dana yang telah ditransfer dan pengembalian kepada rekening pelapor yang sah.",
    evidences: ["Bukti transfer.pdf", "Screenshot status withdrawal.png", "Riwayat percakapan CS.png"],
    reporterName: "Wahyu Setiadi",
    reporterCity: "Malang, Jawa Timur",
    escalationReason: "Sengketa kepemilikan dana bernilai tinggi dengan indikasi kesalahan rekening tujuan pada sistem platform.",
    timeline: [
      { datetime: "12 Jun 2026, 11:00", actor: "Sistem", role: "Sistem", action: "Pengaduan diterima", note: "Tiket BPP-2026-000195 dibuat otomatis.", status: "info" },
      { datetime: "12 Jun 2026, 12:00", actor: "Sistem Verifikasi", role: "Bappebti", action: "Verifikasi awal selesai", note: "Diteruskan ke platform PT Indodax Nasional Indonesia.", status: "success" },
      { datetime: "13 Jun 2026, 15:00", actor: "Tim Operasional Platform", role: "Platform", action: "Tanggapan awal", note: "Platform menyatakan dana telah ditransfer namun ke rekening yang tidak sesuai data pelapor.", status: "warning" },
      { datetime: "14 Jun 2026, 09:00", actor: "Dewi Anjani", role: "Bappebti", action: "Kasus diambil alih", note: "Bappebti mengambil alih kasus sebagai BAPPEBTI OWNED karena dugaan kesalahan sistemik dan nilai sengketa tinggi.", status: "danger" },
      { datetime: "15 Jun 2026, 14:00", actor: "Dewi Anjani", role: "Bappebti", action: "Permintaan data rekonsiliasi", note: "Meminta data rekonsiliasi transfer dari platform dan kliring terkait.", status: "info" },
    ],
    clarifications: [
      { from: "Dewi Anjani", role: "Bappebti", datetime: "15 Jun 2026, 14:05", message: "Mohon platform melampirkan bukti instruksi transfer dan data rekening tujuan yang digunakan saat proses penutupan akun.", kind: "formal-request" },
    ],
    workflowState: "BAPPEBTI_OPERATIONAL_REVIEW",
    publicStatus: "Dalam Review Bappebti",
    financialExposure: 89000000,
    institution: {
      regulatoryOwner: "Bappebti",
      leadInstitution: "PT Indodax Nasional Indonesia",
      currentActionOwner: "Bappebti",
      caseOfficer: "Dewi Anjani",
      supportingInstitutions: ["Kliring Aset Digital Nusantara"],
      bursa: "Bursa Aset Kripto Indonesia",
      clearing: "Kliring Aset Digital Nusantara",
      decisionAuthority: "Bappebti Supervisor",
      escalationLevel: 3,
      escalationReason: "Sengketa kepemilikan dana bernilai tinggi dengan indikasi kesalahan rekening tujuan pada sistem platform.",
    },
  },
];

export const INCIDENTS: IncidentRecord[] = [
  {
    id: "INC-2026-004",
    title: "Pola keterlambatan transaksi lintas platform terkait bank kustodian",
    description:
      "Beberapa pelapor pada platform berbeda melaporkan keterlambatan penarikan dan deposit dana pada rentang waktu yang berdekatan, dengan pola kegagalan konfirmasi dari bank kustodian yang sama.",
    leadInstitution: "Bappebti",
    affectedEntities: ["PT Bursa Digital Nusantara", "PT Indodax Nasional Indonesia"],
    relatedCaseCount: 2,
    estimatedConsumersAffected: 46,
    estimatedFinancialExposure: 37500000,
    rootCause: "Diduga keterlambatan sistem konfirmasi pada bank kustodian bersama, belum dikonfirmasi.",
    severity: "Tinggi",
    status: "Aktif",
    commandOwner: "Dewi Anjani (Bappebti Case Officer)",
    publicCommunicationStatus: "Disiapkan",
    correctiveActions: "Koordinasi dengan bank kustodian untuk mempercepat proses konfirmasi transaksi tertunda.",
    preventiveActions: "Evaluasi SLA konfirmasi bank kustodian dan potensi kewajiban notifikasi dini ke platform anggota.",
    startDate: "13 Jun 2026",
    relatedCases: ["BPP-2026-000184", "BPP-2026-000190"],
  },
];

export const MEMBERS: Member[] = [
  {
    name: "PT Bursa Digital Nusantara",
    type: "Pialang Berjangka",
    license: "PBK-001/BAPPEBTI/2019",
    status: "Aktif",
    bursa: "Bursa Komoditi Nusantara",
    kliring: "Kliring Berjangka Indonesia",
    totalCases: 18,
    handled: 15,
    unhandled: 3,
    slaBreach: 1,
    critical: 0,
    avgResolution: "1.8 hari",
    slaPercent: 94,
    risk: "Rendah",
    category: "Dana / Withdrawal",
    trend: "stabil",
  },
  {
    name: "PT Indodax Nasional Indonesia",
    type: "Pedagang Aset Kripto",
    license: "PFAK-014/BAPPEBTI/2021",
    status: "Aktif",
    bursa: "Bursa Aset Kripto Indonesia",
    kliring: "Kliring Aset Digital Nusantara",
    totalCases: 27,
    handled: 21,
    unhandled: 6,
    slaBreach: 3,
    critical: 1,
    avgResolution: "2.6 hari",
    slaPercent: 81,
    risk: "Sedang",
    category: "Penutupan akun",
    trend: "naik",
  },
  {
    name: "PT Crypto Indonesia Berkat",
    type: "Pedagang Aset Kripto",
    license: "PFAK-022/BAPPEBTI/2021",
    status: "Aktif",
    bursa: "Bursa Aset Kripto Indonesia",
    kliring: "Kliring Aset Digital Nusantara",
    totalCases: 14,
    handled: 9,
    unhandled: 5,
    slaBreach: 2,
    critical: 1,
    avgResolution: "3.4 hari",
    slaPercent: 72,
    risk: "Tinggi",
    category: "Transaksi tidak dikenali",
    trend: "naik",
  },
  {
    name: "PT Pintu Kemana Saja",
    type: "Pedagang Aset Kripto",
    license: "PFAK-031/BAPPEBTI/2022",
    status: "Aktif",
    bursa: "Bursa Aset Kripto Indonesia",
    kliring: "Kliring Aset Digital Nusantara",
    totalCases: 9,
    handled: 8,
    unhandled: 1,
    slaBreach: 0,
    critical: 0,
    avgResolution: "1.5 hari",
    slaPercent: 97,
    risk: "Rendah",
    category: "Settlement / Kliring",
    trend: "turun",
  },
  {
    name: "PT Monex Investindo Futures",
    type: "Pialang Berjangka",
    license: "PBK-006/BAPPEBTI/2017",
    status: "Aktif",
    bursa: "Bursa Berjangka Jakarta",
    kliring: "Kliring Berjangka Indonesia",
    totalCases: 21,
    handled: 14,
    unhandled: 7,
    slaBreach: 4,
    critical: 0,
    avgResolution: "3.9 hari",
    slaPercent: 68,
    risk: "Tinggi",
    category: "Layanan / respon platform",
    trend: "naik",
  },
  {
    name: "PT Rifan Financindo Berjangka",
    type: "Pialang Berjangka",
    license: "PBK-009/BAPPEBTI/2018",
    status: "Aktif",
    bursa: "Bursa Berjangka Jakarta",
    kliring: "Kliring Berjangka Indonesia",
    totalCases: 11,
    handled: 9,
    unhandled: 2,
    slaBreach: 1,
    critical: 1,
    avgResolution: "2.2 hari",
    slaPercent: 86,
    risk: "Sedang",
    category: "Dugaan penipuan / fraud",
    trend: "stabil",
  },
];

export const FEEDBACK_LIST: FeedbackItem[] = [
  {
    id: "FB-2026-0012",
    type: "Kritik",
    topic: "Alur registrasi",
    message: "Proses registrasi terlalu panjang dan formulir verifikasi nomor HP sering gagal terkirim.",
    source: "Situs Publik",
    pic: "Belum ditugaskan",
    status: "Belum Ditugaskan",
    createdAt: "13 Jun 2026, 10:00",
  },
  {
    id: "FB-2026-0013",
    type: "Masukan",
    topic: "Notifikasi status",
    message: "Akan lebih baik jika ada notifikasi WhatsApp setiap kali status tiket berubah, tidak hanya email.",
    source: "Situs Publik",
    pic: "Tim Produk Bappebti",
    status: "Ditinjau",
    createdAt: "14 Jun 2026, 08:20",
  },
  {
    id: "FB-2026-0014",
    type: "Masukan",
    topic: "Edukasi platform berizin",
    message: "Perlu disediakan daftar mudah dicari untuk mengecek apakah sebuah platform sudah berizin Bappebti.",
    source: "Situs Publik",
    pic: "Tim Edukasi Bappebti",
    status: "Selesai",
    createdAt: "11 Jun 2026, 16:45",
  },
  {
    id: "FB-2026-0015",
    type: "Kritik",
    topic: "Waktu respon klarifikasi",
    message: "Permintaan klarifikasi dari platform sering tidak dijawab tepat waktu meski sudah ada SLA.",
    source: "Situs Publik",
    pic: "Tim Pengawasan Bappebti",
    status: "Dikonversi",
    createdAt: "10 Jun 2026, 09:30",
  },
];

export const ADMIN_USERS: AdminUser[] = [
  { name: "Dewi Anjani", email: "dewi.anjani@bappebti.go.id", role: "Bappebti Regulator", organization: "Bappebti", status: "Aktif", lastLogin: "15 Jun 2026, 08:10" },
  { name: "Rangga Saputra", email: "rangga.saputra@bappebti.go.id", role: "Bappebti Regulator", organization: "Bappebti", status: "Aktif", lastLogin: "15 Jun 2026, 07:55" },
  { name: "Tim Operasional Platform", email: "ops@bursadigitalnusantara.co.id", role: "Platform / Pialang", organization: "PT Bursa Digital Nusantara", status: "Aktif", lastLogin: "15 Jun 2026, 09:00" },
  { name: "Tim Supervisi Bursa", email: "supervisi@bursaberjangkajakarta.co.id", role: "Bursa", organization: "Bursa Berjangka Jakarta", status: "Aktif", lastLogin: "15 Jun 2026, 09:40" },
  { name: "Tim Rekonsiliasi Kliring", email: "rekonsiliasi@kliringberjangka.co.id", role: "Kliring", organization: "Kliring Berjangka Indonesia", status: "Aktif", lastLogin: "15 Jun 2026, 10:00" },
  { name: "Sekretariat Asosiasi", email: "sekretariat@asosiasipbk.or.id", role: "Asosiasi", organization: "Asosiasi Pialang Berjangka Indonesia", status: "Aktif", lastLogin: "14 Jun 2026, 17:00" },
  { name: "Andra Wicaksono", email: "andra.wicaksono@email.com", role: "Public User", organization: "-", status: "Aktif", lastLogin: "14 Jun 2026, 21:10" },
  { name: "Galih Saputro", email: "galih.saputro@email.com", role: "Public User", organization: "-", status: "Menunggu Persetujuan", lastLogin: "-" },
  { name: "Operator Baru", email: "operator.baru@bappebti.go.id", role: "Bappebti Regulator", organization: "Bappebti", status: "Menunggu Persetujuan", lastLogin: "-" },
  { name: "Akun Nonaktif Lama", email: "lama.akun@bappebti.go.id", role: "Admin", organization: "Bappebti", status: "Nonaktif", lastLogin: "02 Mei 2026, 10:00" },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  { timestamp: "15 Jun 2026, 14:05", actor: "Dewi Anjani", role: "Bappebti Regulator", action: "Permintaan data rekonsiliasi", object: "BPP-2026-000195", before: "Diproses", after: "Diproses" },
  { timestamp: "15 Jun 2026, 11:00", actor: "Rangga Saputra", role: "Bappebti Regulator", action: "Eskalasi ke Penegakan", object: "BPP-2026-000189", before: "Bappebti Owned", after: "Eskalasi Penegakan" },
  { timestamp: "15 Jun 2026, 10:00", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Pengingat dikirim ke platform", object: "BPP-2026-000187", before: "Menunggu Klarifikasi", after: "Menunggu Klarifikasi" },
  { timestamp: "15 Jun 2026, 09:30", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Ambil alih current owner", object: "BPP-2026-000193", before: "Platform", after: "Bursa" },
  { timestamp: "14 Jun 2026, 13:20", actor: "Tim Supervisi Bursa", role: "Bursa", action: "Eskalasi diterima dari platform", object: "BPP-2026-000187", before: "Platform", after: "Bursa" },
  { timestamp: "14 Jun 2026, 10:15", actor: "Dewi Anjani", role: "Bappebti Regulator", action: "Ambil alih sebagai Bappebti-owned", object: "BPP-2026-000185", before: "Member Assigned", after: "Bappebti Owned" },
  { timestamp: "14 Jun 2026, 09:00", actor: "Dewi Anjani", role: "Bappebti Regulator", action: "Ambil alih sebagai Bappebti-owned", object: "BPP-2026-000195", before: "Member Assigned", after: "Bappebti Owned" },
  { timestamp: "13 Jun 2026, 17:00", actor: "Sistem", role: "Sistem", action: "SLA terlampaui", object: "BPP-2026-000185", before: "Aman", after: "Lewat SLA" },
  { timestamp: "12 Jun 2026, 11:05", actor: "Sistem", role: "Sistem", action: "Routing kasus ke platform", object: "BPP-2026-000184", before: "Sistem Verifikasi", after: "Platform" },
  { timestamp: "12 Jun 2026, 09:14", actor: "Andra Wicaksono", role: "Public User", action: "Membuat pengaduan baru", object: "BPP-2026-000184", before: "-", after: "Baru" },
];

export const NOTIFICATIONS: NotificationItem[] = [
  { time: "15 Jun 2026, 09:46", ticket: "BPP-2026-000190", type: "Permintaan Klarifikasi", message: "Platform meminta bukti transfer dengan kualitas lebih jelas.", status: "Belum Dibaca" },
  { time: "14 Jun 2026, 16:45", ticket: "BPP-2026-000188", type: "Resolusi Diajukan", message: "Platform mengajukan resolusi penutupan akun. Mohon konfirmasi.", status: "Belum Dibaca" },
  { time: "14 Jun 2026, 15:40", ticket: "BPP-2026-000184", type: "Update Status", message: "Tim platform sedang menunggu konfirmasi bank terkait penarikan dana Anda.", status: "Dibaca" },
  { time: "13 Jun 2026, 11:02", ticket: "BPP-2026-000184", type: "Verifikasi Selesai", message: "Pengaduan Anda telah lolos verifikasi awal dan diteruskan ke platform.", status: "Dibaca" },
  { time: "12 Jun 2026, 09:15", ticket: "BPP-2026-000184", type: "Tiket Dibuat", message: "Pengaduan Anda telah diterima dengan nomor tiket BPP-2026-000184.", status: "Dibaca" },
];

export function getCaseByTicket(ticket: string): ComplaintCase | undefined {
  return CASES.find((c) => c.ticket === ticket);
}

export function getIncidentById(id: string): IncidentRecord | undefined {
  return INCIDENTS.find((i) => i.id === id);
}

/** @deprecated use formatCurrencyIDR from lib/format.ts — kept for existing pages */
export { formatCurrencyIDR as formatCurrency } from "./format";
